trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: test   # Replace with your actual variable group name

stages:
- stage: ReplaceAndPublish
  jobs:
  - job: ReplaceAndExport
    displayName: 'Replace tokens and publish .properties file'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - bash: |
        echo "##[group]Variables from test"
        # Print all variables with the MYGROUP_ prefix
        printenv | grep ^MYGROUP_ | sort
        echo "##[endgroup]"
      displayName: 'List variables from specific group'

    # Publish the modified file as an artifact
    - task: PublishBuildArtifacts@1
      displayName: 'Publish properties file as artifact'
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/application-prod_scheduler.properties'
        ArtifactName: 'scheduler-config'
        publishLocation: 'Container'
